

Member.create(first_name:"Andy", last_name:"Rackaskaus", email:"andrewrackauskas@yahoo.com", password: "testpass")
Member.create(first_name:"Ben", last_name:"Davis", email:"benjaminedavis@gmail.com", password: "testpass")
Member.create(first_name:"Keith", last_name:"Wilson", email:"kwilsinca@gmail.com ", password: "testpass")
Member.create(first_name:"Kevin", last_name:"Robie", email:"kevinr@robiedesign.com", password: "testpass")
Member.create(first_name:"Matt", last_name:"Granger", email:"grangerdanger@earthlink.net", password: "testpass")
Member.create(first_name:"Robert", last_name:"Granger", email:"robertgranger@yahoo.com", password: "testpass")
Member.create(first_name:"Al", last_name:"Lagrosa", email:"re_al_80@yahoo.com", password: "testpass")
Member.create(first_name:"James", last_name:"Chen", email:"james.chen@13east.com ", password: "testpass")
Member.create(first_name:"Paul", last_name:"Moore", email:"paulrmoore@sbcglobal.net", password: "testpass")
Member.create(first_name:"Kirk", last_name:"Duncan", email:"kirk0605@yahoo.com", password: "testpass")
Member.create(first_name:"Brian", last_name:"Gibney", email:"brianggibney@gmail.com ", password: "testpass")
Member.create(first_name:"Dan", last_name:"Choi", email:"dc@gmail.com", password: "testpass")
Member.create(first_name:"David", last_name:"Ivy", email:"di@gmail.com", password: "testpass")
Member.create(first_name:"Mike", last_name:"Roth", email:"mr@gmail.com", password: "testpass")
Member.create(first_name:"Ron", last_name:"Simms", email:"rs@gmail.com", password: "testpass")
Member.create(first_name:"Mike", last_name:"Ochs", email:"mo@gmail.com", password: "testpass")
Member.create(first_name:"Johnny", last_name:"Tu", email:"johnnyt@pacificwestlitho.com", password: "testpass")
Member.create(first_name:"John", last_name:"McLean", email:"jm@gmail.com", password: "testpass")
Member.create(first_name:"Ed", last_name:"Vigdor", email:"ev@gmail.com", password: "testpass")
Member.create(first_name:"Brian", last_name:"Patrick", email:"brianpatrickw@gmail.com", password: "testpass")

Event.create(date:"2006-05-20", host: "Andy Rackaskaus", theme: "The Inception!", description: "Single Malt Scotch")
Event.create(date:"2006-07-15", host: "Kevin Robie", description: "Single Malt Scotch")
Event.create(date:"2006-11-11", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"2007-03-17", host: "Andy Rackaskaus", theme: "St. Patrick's Day!", description: "Irish Whiskey")
Event.create(date:"2007-06-09", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"2008-09-20", host: "Kevin Robie", description: "Single Malt Scotch")
Event.create(date:"2009-02-28", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"2009-05-09", host: "John McLean", description: "Single Malt Scotch")
Event.create(date:"2009-09-26", host: "Brian Walsh", description: "Single Malt Scotch")
Event.create(date:"2010-02-20", host: "Andy Rackaskaus", theme: "President's Day!", description: "American Whiskey")
Event.create(date:"2011-10-22", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"2012-02-19", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"2012-07-28", host: "Andy Rackaskaus", theme: "American Whiskey!", description: "American Whiskey")
Event.create(date:"2013-04-13", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"2013-07-14", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"2013-11-02", host: "Andy Rackaskaus", theme: "Free For All!", description: "All Whiskey Types")
Event.create(date:"2014-01-25", host: "Andy Rackaskaus", theme: "Free For All!", description: "All Whiskey Types")
Event.create(date:"2015-04-25", host: "Andy Rackaskaus", theme: "Free For All!", description: "All Whiskey Types")

EventMember.create(event_id: 1, member_id: 1, attended: true)
EventMember.create(event_id: 1, member_id: 2, attended: true)
EventMember.create(event_id: 1, member_id: 3, attended: true)
EventMember.create(event_id: 1, member_id: 4, attended: true)
EventMember.create(event_id: 1, member_id: 5, attended: true)
EventMember.create(event_id: 1, member_id: 6, attended: true)
EventMember.create(event_id: 1, member_id: 9, attended: true)
EventMember.create(event_id: 1, member_id: 13, attended: true)

EventMember.create(event_id: 2, member_id: 1, attended: true)
EventMember.create(event_id: 2, member_id: 2, attended: true)
EventMember.create(event_id: 2, member_id: 3, attended: true)
EventMember.create(event_id: 2, member_id: 4, attended: true)
EventMember.create(event_id: 2, member_id: 6, attended: true)
EventMember.create(event_id: 2, member_id: 9, attended: true)
EventMember.create(event_id: 2, member_id: 13, attended: true)
EventMember.create(event_id: 2, member_id: 15, attended: true)

EventMember.create(event_id: 3, member_id: 1, attended: true)
EventMember.create(event_id: 3, member_id: 2, attended: true)
EventMember.create(event_id: 3, member_id: 3, attended: true)
EventMember.create(event_id: 3, member_id: 4, attended: true)
EventMember.create(event_id: 3, member_id: 5, attended: true)
EventMember.create(event_id: 3, member_id: 6, attended: true)
EventMember.create(event_id: 3, member_id: 9, attended: true)
EventMember.create(event_id: 3, member_id: 13, attended: true)

EventMember.create(event_id: 4, member_id: 1, attended: true)
EventMember.create(event_id: 4, member_id: 3, attended: true)
EventMember.create(event_id: 4, member_id: 4, attended: true)
EventMember.create(event_id: 4, member_id: 7, attended: true)
EventMember.create(event_id: 4, member_id: 9, attended: true)

EventMember.create(event_id: 5, member_id: 1, attended: true)
EventMember.create(event_id: 5, member_id: 3, attended: true)
EventMember.create(event_id: 5, member_id: 4, attended: true)
EventMember.create(event_id: 5, member_id: 5, attended: true)
EventMember.create(event_id: 5, member_id: 6, attended: true)
EventMember.create(event_id: 5, member_id: 13, attended: true)

EventMember.create(event_id: 6, member_id: 1, attended: true)
EventMember.create(event_id: 6, member_id: 2, attended: true)
EventMember.create(event_id: 6, member_id: 4, attended: true)
EventMember.create(event_id: 6, member_id: 9, attended: true)
EventMember.create(event_id: 6, member_id: 18, attended: true)
EventMember.create(event_id: 6, member_id: 19, attended: true)

EventMember.create(event_id: 7, member_id: 1, attended: true)
EventMember.create(event_id: 7, member_id: 2, attended: true)
EventMember.create(event_id: 7, member_id: 3, attended: true)
EventMember.create(event_id: 7, member_id: 4, attended: true)
EventMember.create(event_id: 7, member_id: 6, attended: true)
EventMember.create(event_id: 7, member_id: 9, attended: true)
EventMember.create(event_id: 7, member_id: 11, attended: true)

EventMember.create(event_id: 8, member_id: 1, attended: true)
EventMember.create(event_id: 8, member_id: 2, attended: true)
EventMember.create(event_id: 8, member_id: 5, attended: true)
EventMember.create(event_id: 8, member_id: 6, attended: true)
EventMember.create(event_id: 8, member_id: 9, attended: true)
EventMember.create(event_id: 8, member_id: 20, attended: true)

EventMember.create(event_id: 9, member_id: 1, attended: true)
EventMember.create(event_id: 9, member_id: 2, attended: true)
EventMember.create(event_id: 9, member_id: 6, attended: true)
EventMember.create(event_id: 9, member_id: 9, attended: true)
EventMember.create(event_id: 9, member_id: 16, attended: true)
EventMember.create(event_id: 9, member_id: 18, attended: true)

EventMember.create(event_id: 10, member_id: 1, attended: true)
EventMember.create(event_id: 10, member_id: 3, attended: true)
EventMember.create(event_id: 10, member_id: 5, attended: true)
EventMember.create(event_id: 10, member_id: 14, attended: true)

EventMember.create(event_id: 11, member_id: 1, attended: true)
EventMember.create(event_id: 11, member_id: 2, attended: true)
EventMember.create(event_id: 11, member_id: 3, attended: true)
EventMember.create(event_id: 11, member_id: 6, attended: true)
EventMember.create(event_id: 11, member_id: 7, attended: true)

EventMember.create(event_id: 12, member_id: 1, attended: true)
EventMember.create(event_id: 12, member_id: 2, attended: true)
EventMember.create(event_id: 12, member_id: 3, attended: true)
EventMember.create(event_id: 12, member_id: 4, attended: true)
EventMember.create(event_id: 12, member_id: 6, attended: true)
EventMember.create(event_id: 12, member_id: 7, attended: true)
EventMember.create(event_id: 12, member_id: 9, attended: true)
EventMember.create(event_id: 12, member_id: 10, attended: true)

EventMember.create(event_id: 13, member_id: 1, attended: true)
EventMember.create(event_id: 13, member_id: 2, attended: true)
EventMember.create(event_id: 13, member_id: 7, attended: true)
EventMember.create(event_id: 13, member_id: 9, attended: true)

EventMember.create(event_id: 14, member_id: 1, attended: true)
EventMember.create(event_id: 14, member_id: 2, attended: true)

EventMember.create(event_id: 15, member_id: 1, attended: true)
EventMember.create(event_id: 15, member_id: 7, attended: true)

EventMember.create(event_id: 16, member_id: 1, attended: true)
EventMember.create(event_id: 16, member_id: 2, attended: true)
EventMember.create(event_id: 16, member_id: 3, attended: true)
EventMember.create(event_id: 16, member_id: 4, attended: true)
EventMember.create(event_id: 16, member_id: 6, attended: true)
EventMember.create(event_id: 16, member_id: 7, attended: true)
EventMember.create(event_id: 16, member_id: 8, attended: true)
EventMember.create(event_id: 16, member_id: 12, attended: true)

EventMember.create(event_id: 17, member_id: 1, attended: true)
EventMember.create(event_id: 17, member_id: 3, attended: true)
EventMember.create(event_id: 17, member_id: 5, attended: true)
EventMember.create(event_id: 17, member_id: 6, attended: true)
EventMember.create(event_id: 17, member_id: 7, attended: true)
EventMember.create(event_id: 17, member_id: 8, attended: true)
EventMember.create(event_id: 17, member_id: 10, attended: true)

EventMember.create(event_id: 18, member_id: 1, attended: true)
EventMember.create(event_id: 18, member_id: 2, attended: true)
EventMember.create(event_id: 18, member_id: 8, attended: true)
EventMember.create(event_id: 18, member_id: 17, attended: true)


Whiskey.create(name: "1792 Ridgemont Reserve", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 3, price: 45, abv: 0.47, pic1: "https://img.thewhiskyexchange.com/540/brbon_rid1.jpg", event_id: 18, member_id: 8)
Whiskey.create(name: "Aberlour Abunah", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 70, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/ablob.non27.jpg", event_id: 1, member_id: 9)
Whiskey.create(name: "Angels Envy", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 6, price: 45, abv: 0.433, pic1: "https://img.thewhiskyexchange.com/540/brbon_ang2.jpg", event_id: 16, member_id: 4)
Whiskey.create(name: "Ardbeg 10", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 45, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/900/abgob.10yov1.jpg", event_id: 7, member_id: 11)
Whiskey.create(name: "Ardbeg Alligator", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: "", price: 120, abv: 0.512, pic1: "https://img.thewhiskyexchange.com/540/abgob.non10.jpg", event_id: 12, member_id: 4)
Whiskey.create(name: "Ardbeg Corrywreckan", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 75, abv: 0.57, pic1: "https://img.thewhiskyexchange.com/540/abgob.non2.jpg", event_id: 17, member_id: 3)
Whiskey.create(name: "Ardbeg Supernova 2010", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 2, price: 160, abv: 0.55, pic1: "https://img.thewhiskyexchange.com/900/abgob.non8.jpg", event_id: 12, member_id: 7)
Whiskey.create(name: "Ardbeg Uigeadail", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 65, abv: 0.542, pic1: "https://img.thewhiskyexchange.com/900/abgob.10yov1.jpg", event_id: 11, member_id: 7)
Whiskey.create(name: "Ardmore", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 9, price: 35, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/ardob.non.jpg", event_id: 7, member_id: 6)
Whiskey.create(name: "Arran Malt", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 73, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/900/arrob.non35.jpg", event_id: 12, member_id: 3)
Whiskey.create(name: "Auchentoshan", region: "Lowland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 30, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/aucob.non3.jpg", event_id: 1, member_id: 1)
Whiskey.create(name: "Auchentoshan Bordeaux Cask", region: "Lowland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 11, price: 65, abv: 0.58, pic1: "https://img.thewhiskyexchange.com/540/aucob.1999.jpg", event_id: 13, member_id: 1)
Whiskey.create(name: "Auchriosk Murray McDavid", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 65, abv: 0.46, pic1: "http://www.grauonline.eu/img/productos/murray-mc-david-auchroisk-1992__WHI0905.jpg", event_id: 8, member_id: 9)
Whiskey.create(name: "Balcones 1", region: "Texas", country: "USA", wtype: "Corn", malt: "Single Malt", age: "", price: 50, abv: 0.505, pic1: "https://img.thewhiskyexchange.com/900/brbon_bal4.jpg", event_id: 16, member_id: 2)
Whiskey.create(name: "Balvenie 15", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 60, abv: 0.478, pic1: "https://img.thewhiskyexchange.com/540/balob.15yo.jpg", event_id: 1, member_id: 2)
Whiskey.create(name: "Balvenie Caribbbean Rum Cask", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 60, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/balob.14yov4.jpg", event_id: 11, member_id: 3)
Whiskey.create(name: "Basil Haydens", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 8, price: 45, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/brbon_bas1.jpg", event_id: 16, member_id: 2)
Whiskey.create(name: "Ben Riach 15", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 75, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/900/bnrob.15yov1.jpg", event_id: 7, member_id: 3)
Whiskey.create(name: "Benromach", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 9, price: 50, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/brmob.10yov1.jpg", event_id: 2, member_id: 6)
Whiskey.create(name: "Bernheim Original Small Batch Wheated", region: "Kentucky", country: "USA", wtype: "Wheat", malt: "Blend", age: 3, price: 50, abv: 0.45, pic1: "https://img.thewhiskyexchange.com/540/brbon_ber1.jpg", event_id: 18, member_id: 8)
Whiskey.create(name: "Bowmore 1996 Non-Chill Filtered David MacMurray", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 75, abv: 0.47, pic1: "https://img.thewhiskyexchange.com/900/bowob.non42.jpg", event_id: 17, member_id: 1)
Whiskey.create(name: "Bowmore Feis Ilse 2009", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 9, price: 110, abv: 0.571, pic1: "https://img.thewhiskyexchange.com/540/bowob.1999v1.jpg", event_id: 11, member_id: 1)
Whiskey.create(name: "Bowmore Rattray 1996 Bottling", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 17, price: 100, abv: 0.55, pic1: "https://img.thewhiskyexchange.com/540/bowob.12yov14.jpg", event_id: 17, member_id: 5)
Whiskey.create(name: "Brechin Cadenhead Cask Str North Port", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 20, price: 136, abv: 0.55, pic1: "https://img.thewhiskyexchange.com/270/nptrm.1979.jpg", event_id: 11, member_id: 6)
Whiskey.create(name: "Bruichladdich 12", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 40, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/bruob.12yo.jpg", event_id: 8, member_id: 5)
Whiskey.create(name: "Bruichladdich 15", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 60, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/bruob.15yo.jpg", event_id: 8, member_id: 5)
Whiskey.create(name: "Bruichladdich 2nd Edition", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 80, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/bruob.15yo.jpg", event_id: 16, member_id: 8)
Whiskey.create(name: "Bruichladdich Bourbon Aged Cask", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 16, price: 90, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/bruob.16yo.jpg", event_id: 15, member_id: 7)
Whiskey.create(name: "Bruichladdich Ochdamhmor", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 5, price: 160, abv: 0.59, pic1: "https://houseofwhiskey.co.nz/wp-content/uploads/whiskey_images/Octomore_5.jpg", event_id: 11, member_id: 1)
Whiskey.create(name: "Bruichladdich Port Charlotte Peat Project", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: "", price: 70, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/pclob.non2.jpg", event_id: 16, member_id: 1)
Whiskey.create(name: "Buffalo Trace Experimental #7 Double Char", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 15, price: 60, abv: 0.45, pic1: "https://img.thewhiskyexchange.com/900/brbon_buf13.jpg", event_id: 16, member_id: 7)
Whiskey.create(name: "Bunnahabain 12", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 45, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/bunob.12yov3.jpg", event_id: 8, member_id: 1)
Whiskey.create(name: "Bushmills Black Bush", region: "", country: "Ireland", wtype: "Irish", malt: "Blend", age: "", price: 30, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/irish_bus2.jpg", event_id: 4, member_id: 7)
Whiskey.create(name: "Caol Ila 11", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 11, price: 60, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/cilob.12yov4.jpg", event_id: 1, member_id: 5)
Whiskey.create(name: "Caol Ila 12", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 60, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/cilob.12yov4.jpg", event_id: 3, member_id: 5)
Whiskey.create(name: "Caol Ila 18", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 18, price: 75, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/cilob.18yo.jpg", event_id: 3, member_id: 2)
Whiskey.create(name: "Caol Ila Frisky Whisky Unchillfiltered 2010 Bottling", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 25, price: 150, abv: 0.54, pic1: "https://img.thewhiskyexchange.com/540/cilind1983v1.jpg", event_id: 15, member_id: 7)
Whiskey.create(name: "Carn Mor Cask Non-Chill Filtered", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 60, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/900/bnvcrn1998.jpg", event_id: 14, member_id: 1)
Whiskey.create(name: "Classics of Islay Lagavulin", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 55, abv: 0.54, pic1: "https://img.thewhiskyexchange.com/900/elem_lg3.jpg", event_id: 5, member_id: 1)
Whiskey.create(name: "Classics of Islay Lagavulin", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 26, price: 75, abv: 0.54, pic1: "https://img.thewhiskyexchange.com/900/elem_lg5.jpg", event_id: 7, member_id: 3)
Whiskey.create(name: "Clontarf", region: "", country: "Ireland", wtype: "Irish", malt: "Blend", age: "", price: 20, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/irish_clo3.jpg", event_id: 4, member_id: 4)
Whiskey.create(name: "Clynelish", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 60, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/900/clyob.14yov1.jpg", event_id: 16, member_id: 12)
Whiskey.create(name: "Colonel E.H. Taylor", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Single Malt", age: 6, price: 65, abv: 0.5, pic1: "https://img.thewhiskyexchange.com/540/brbon_eht3.jpg", event_id: 16, member_id: 3)
Whiskey.create(name: "Connemara", region: "", country: "Ireland", wtype: "Irish (peated)", malt: "Single Malt", age: 10, price: 35, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/irish_con2.jpg", event_id: 4, member_id: 1)
Whiskey.create(name: "Cragganmore", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 50, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/cgmob.12yov2.jpg", event_id: 3, member_id: 5)
Whiskey.create(name: "Cutlers Artisan Distillery 33", region: "California", country: "USA", wtype: "Bourbon", malt: "Blend", age: 6, price: 35, abv: 0.43, pic1: "", event_id: 16, member_id: 1)
Whiskey.create(name: "Dalmore", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 30, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/dlmob.15yo.jpg", event_id: 1, member_id: 3)
Whiskey.create(name: "Dalwhinnie", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 60, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/dalob.15yov1.jpg", event_id: 6, member_id: 18)
Whiskey.create(name: "Deanston", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 36, abv: 0.463, pic1: "https://img.thewhiskyexchange.com/900/dstob.non3.jpg", event_id: 9, member_id: 6)
Whiskey.create(name: "Edradour", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 60, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/edrob.12yo.jpg", event_id: 3, member_id: 9)
Whiskey.create(name: "Ellenstown", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 60, abv: 0.46, pic1: "http://www.jewmalt.com/wp-content/uploads/2010/05/1023042x.jpg", event_id: 3, member_id: 4)
Whiskey.create(name: "Four Roses Single Barrel", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 3, price: 40, abv: 0.5, pic1: "https://img.thewhiskyexchange.com/900/brbon_fou9.jpg", event_id: 13, member_id: 7)
Whiskey.create(name: "Glen Garioch", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 70, abv: 0.48, pic1: "https://img.thewhiskyexchange.com/900/ggrob.12yo.jpg", event_id: 5, member_id: 6)
Whiskey.create(name: "Glen Moray", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 30, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/gmyob.12yov3.jpg", event_id: 3, member_id: 13)
Whiskey.create(name: "Glen Taite McCallan Bottling", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 19, price: 89, abv: 0.4, pic1: "", event_id: 7, member_id: 1)
Whiskey.create(name: "Glenfarclas 12", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 35, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/gfcob.12yov1.jpg", event_id: 2, member_id: 15)
Whiskey.create(name: "Glengoyne", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 17, price: 65, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/900/ggoob.17yo.jpg", event_id: 3, member_id: 3)
Whiskey.create(name: "Glenkinchie (OMIT)", region: "Lowland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 50, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/gkcob.12yov1.jpg", event_id: 9, member_id: 18)
Whiskey.create(name: "Glenlivet 12", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 35, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/glvob.12yov1.jpg", event_id: 9, member_id: 1)
Whiskey.create(name: "Glenmorangie 10", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 35, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/gmgob.10yov21.jpg", event_id: 2, member_id: 13)
Whiskey.create(name: "Glenmorangie Finealta", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 9, price: 120, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/gmgob.non29.jpg", event_id: 17, member_id: 5)
Whiskey.create(name: "Glenmorangie Nectar D'Or", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 70, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/gmgob.12yov7.jpg", event_id: 7, member_id: 4)
Whiskey.create(name: "Glenrothes Signatory", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 60, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/grssig1997v1.jpg", event_id: 2, member_id: 3)
Whiskey.create(name: "High West Campfire", region: "Utah", country: "USA", wtype: "Blend", malt: "Blend", age: "", price: 50, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/brbon_hig5.jpg", event_id: 16, member_id: 3)
Whiskey.create(name: "High West Rendezvous", region: "Utah", country: "USA", wtype: "Rye", malt: "Blend", age: "", price: 50, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/brbon_hig3.jpg", event_id: 10, member_id: 3)
Whiskey.create(name: "Highland Park 15", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 50, abv: "", pic1: "https://img.thewhiskyexchange.com/540/hlpob.12yov8.jpg", event_id: 2, member_id: 2)
Whiskey.create(name: "Highland Park 18", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 18, price: 60, abv: "", pic1: "https://img.thewhiskyexchange.com/540/hlpob.18yov2.jpg", event_id: 6, member_id: 4)
Whiskey.create(name: "Hudson Baby Bourbon", region: "New York", country: "USA", wtype: "Bourbon", malt: "Blend", age: "", price: 45, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/brbon_hud1.jpg", event_id: 13, member_id: 2)
Whiskey.create(name: "Hudson Double Charred Whiskey", region: "New York", country: "USA", wtype: "Bourbon", malt: "Blend", age: 4, price: 50, abv: 0.46, pic1: "http://www.drinkupny.com/v/vspfiles/photos/S1613-2.jpg", event_id: 18, member_id: 2)
Whiskey.create(name: "Imperial Signatory", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 16, price: 61, abv: "", pic1: "https://img.thewhiskyexchange.com/900/impsig1995v12.jpg", event_id: 8, member_id: 20)
Whiskey.create(name: "Imperial Signatory 1995 Bottling", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 17, price: 70, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/900/impsig1995v11.jpg", event_id: 17, member_id: 6)
Whiskey.create(name: "Isle of Jura", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: "", price: 65, abv: "", pic1: "https://img.thewhiskyexchange.com/540/iojob.non.jpg", event_id: 6, member_id: 1)
Whiskey.create(name: "Jura Prophecy", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: "", price: 73, abv: 0.46, pic1: "http://ecx.images-amazon.com/images/I/81ceGbhDnXL._SY679_.jpg", event_id: 11, member_id: 3)
Whiskey.create(name: "Kavalan Vinlo Barrique Cask Strength", region: "", country: "Taiwan", wtype: "Bourbon", malt: "Blend", age: "", price: 150, abv: 0.578, pic1: "", event_id: 18, member_id: 1)
Whiskey.create(name: "Knappogue", region: "", country: "Ireland", wtype: "Irish", malt: "Single Malt", age: 11, price: 40, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/irish_kna6.jpg", event_id: 1, member_id: 13)
Whiskey.create(name: "Lagavulin", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 16, price: 65, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/lgvob.16yo.jpg", event_id: 2, member_id: 1)
Whiskey.create(name: "Lagavulin Cask Strength 2011 Bottling", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 110, abv: 0.575, pic1: "https://img.thewhiskyexchange.com/540/lgvob.1995.jpg", event_id: 14, member_id: 2)
Whiskey.create(name: "Lagavulin Distillers Edition", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 17, price: 95, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/900/lgvob.1996.jpg", event_id: 8, member_id: 2)
Whiskey.create(name: "Laphroaig 10", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 35, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/900/lrgob.10yov1.jpg", event_id: 1, member_id: 6)
Whiskey.create(name: "Laphroaig 15", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 70, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/lrgob.15yo.jpg", event_id: 6, member_id: 2)
Whiskey.create(name: "Laphroaig 18", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 18, price: 147, abv: 0.48, pic1: "https://img.thewhiskyexchange.com/540/lrgob.non1.jpg", event_id: 12, member_id: 6)
Whiskey.create(name: "Laphroaig Cask Strength", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 80, abv: 0.553, pic1: "https://img.thewhiskyexchange.com/540/lrgob.10yov12.jpg", event_id: 12, member_id: 1)
Whiskey.create(name: "Ledaig", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 50, abv: "", pic1: "https://img.thewhiskyexchange.com/540/ldgob.10yo.jpg", event_id: 1, member_id: 4)
Whiskey.create(name: "Linkwood", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 15, price: 66, abv: "", pic1: "https://img.thewhiskyexchange.com/900/lkwsig1998v3.jpg", event_id: 8, member_id: 6)
Whiskey.create(name: "Loch Fyne Living Cask From Invarary 2011 Bottling", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Blend", age: "", price: 50, abv: 0.58, pic1: "", event_id: 14, member_id: 1)
Whiskey.create(name: "Lochnagar", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 35, abv: "", pic1: "", event_id: 5, member_id: 13)
Whiskey.create(name: "Macallan 12", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 50, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/macob.12yov7.jpg", event_id: 2, member_id: 4)
Whiskey.create(name: "Macallan Signatory", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 70, abv: "", pic1: "", event_id: 5, member_id: 3)
Whiskey.create(name: "Mannochmore Signatory", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 13, price: 85, abv: "", pic1: "https://img.thewhiskyexchange.com/540/mnmsig1991.jpg", event_id: 3, member_id: 6)
Whiskey.create(name: "Macallan 18", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 18, price: 130, abv: "", pic1: "https://img.thewhiskyexchange.com/540/macob.18yo.jpg", event_id: 6, member_id: 4)
Whiskey.create(name: "Macallan Cask Strength", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: "", price: 60, abv: "", pic1: "https://img.thewhiskyexchange.com/900/macob.10yov7.jpg", event_id: 6, member_id: 19)
Whiskey.create(name: "McKenna", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 10, price: 27, abv: 0.5, pic1: "", event_id: 16, member_id: 6)
Whiskey.create(name: "Oban 14", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 60, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/540/obnob.14yo.jpg", event_id: 3, member_id: 1)
Whiskey.create(name: "Oban 18", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 18, price: 120, abv: 0.43, pic1: "https://img.thewhiskyexchange.com/900/obnob.1999.jpg", event_id: 17, member_id: 8)
Whiskey.create(name: "Oban 32", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 32, price: 300, abv: "", pic1: "https://img.thewhiskyexchange.com/540/obnob.1969.jpg", event_id: 5, member_id: 5)
Whiskey.create(name: "Redbreast 12", region: "", country: "Ireland", wtype: "Irish", malt: "Single Malt", age: 12, price: 40, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/irish_red7.jpg", event_id: 4, member_id: 3)
Whiskey.create(name: "Rosebank Gordon & McPhail", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 80, abv: "", pic1: "", event_id: 5, member_id: 5)
Whiskey.create(name: "Russell's Reserve", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 6, price: 36, abv: 0.45, pic1: "https://img.thewhiskyexchange.com/900/brbon_wil39.jpg", event_id: 10, member_id: 14)
Whiskey.create(name: "Scapa 10", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 50, abv: "", pic1: "https://img.thewhiskyexchange.com/540/scpob.12yov1.jpg", event_id: 1, member_id: 5)
Whiskey.create(name: "Scapa 16", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 16, price: 65, abv: "", pic1: "https://img.thewhiskyexchange.com/540/scpob.16yo.jpg", event_id: 7, member_id: 2)
Whiskey.create(name: "Springbank", region: "Campbeltown", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 10, price: 70, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/900/sprob.12yov25.jpg", event_id: 15, member_id: 1)
Whiskey.create(name: "Strathisla Chivas Brothers", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 12, price: 65, abv: "", pic1: "https://img.thewhiskyexchange.com/540/stlob.12yov1.jpg", event_id: 6, member_id: 9)
Whiskey.create(name: "Suntory Yamazuki", region: "", country: "Japan", wtype: "Japanese", malt: "Single Malt", age: 12, price: 40, abv: 0.435, pic1: "https://img.thewhiskyexchange.com/540/japan_yam1.jpg", event_id: 3, member_id: 1)
Whiskey.create(name: "Talisker", region: "Islay", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 18, price: 75, abv: "", pic1: "https://img.thewhiskyexchange.com/540/talob.18yov1.jpg", event_id: 2, member_id: 9)
Whiskey.create(name: "Talisker Distillers Edition", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 11, price: 85, abv: 0.458, pic1: "https://s-media-cache-ak0.pinimg.com/736x/75/f3/85/75f3855ae936a705f40714a9fd485210.jpg", event_id: 18, member_id: 17)
Whiskey.create(name: "Talisker Storm", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: "", price: 75, abv: 0.458, pic1: "https://img.thewhiskyexchange.com/540/talob.non7.jpg", event_id: 18, member_id: 1)
Whiskey.create(name: "Templeton Rye", region: "Iowa", country: "USA", wtype: "Rye", malt: "Blend", age: "", price: 47, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/brbon_tem1.jpg", event_id: 13, member_id: 9)
Whiskey.create(name: "The Peat Monster Compass Box Non-Chill Filtered", region: "Islay/Speyside", country: "Scotland", wtype: "Scotch", malt: "Blend", age: "", price: 60, abv: 0.46, pic1: "https://img.thewhiskyexchange.com/540/vatted_com25.jpg", event_id: 12, member_id: 2)
Whiskey.create(name: "Tomintoul", region: "Speyside", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 16, price: 45, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/900/tmtob.14yo.jpg", event_id: 5, member_id: 4)
Whiskey.create(name: "Tullamore Dew", region: "", country: "Ireland", wtype: "Irish", malt: "Blend", age: "", price: 25, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/irish_tul1.jpg", event_id: 4, member_id: 9)
Whiskey.create(name: "Tullibardine", region: "Highland", country: "Scotland", wtype: "Scotch", malt: "Single Malt", age: 14, price: 60, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/270/tulob.05yov3.jpg", event_id: 9, member_id: 9)
Whiskey.create(name: "Tyrconnel", region: "", country: "Ireland", wtype: "Irish", malt: "Single Malt", age: "", price: 30, abv: 0.4, pic1: "https://img.thewhiskyexchange.com/540/irish_tyr1.jpg", event_id: 7, member_id: 9)
Whiskey.create(name: "Wathens", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 6, price: 25, abv: 0.47, pic1: "", event_id: 16, member_id: 4)
Whiskey.create(name: "Watkins Select", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: 3, price: 35, abv: 0.4, pic1: "https://s-media-cache-ak0.pinimg.com/236x/0e/8f/ba/0e8fbaaad13ac172f2db7ffa707896bb.jpg", event_id: 18, member_id: 2)
Whiskey.create(name: "Wild Turkey Rare Breed Barrel Proof", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: "", price: 34, abv: 0.541, pic1: "https://img.thewhiskyexchange.com/540/brbon_wil5.jpg", event_id: 13, member_id: 1)
Whiskey.create(name: "Willett", region: "Kentucky", country: "USA", wtype: "Bourbon", malt: "Blend", age: "", price: 70, abv: 0.47, pic1: "https://img.thewhiskyexchange.com/900/brbon_wil28.jpg", event_id: 10, member_id: 1)
Whiskey.create(name: "Willett Distillery Family Estate", region: "Kentucky", country: "USA", wtype: "Rye", malt: "Blend", age: 9, price: 56, abv: 0.62, pic1: "https://img.thewhiskyexchange.com/540/brbon_wil26.jpg", event_id: 13, member_id: 1)


Comment.create(member_id: 1, whiskey_id: 1, comment: "burn, orange, water +")
Comment.create(member_id: 1, whiskey_id: 2, comment: "vanilla, smooth")
Comment.create(member_id: 1, whiskey_id: 3, comment: "maple, pepper finish")
Comment.create(member_id: 1, whiskey_id: 4, comment: "burn, salty")
Comment.create(member_id: 1, whiskey_id: 4, comment: "sweet smooth")
Comment.create(member_id: 1, whiskey_id: 5, comment: "smooth")
Comment.create(member_id: 1, whiskey_id: 6, comment: "seaweed, smoke")
Comment.create(member_id: 1, whiskey_id: 7, comment: "smokey, bbq, musky")
Comment.create(member_id: 1, whiskey_id: 8, comment: "Bushmills-y, water +")
Comment.create(member_id: 1, whiskey_id: 9, comment: "young, slight peat, water -")
Comment.create(member_id: 1, whiskey_id: 10, comment: "oomph, water +")
Comment.create(member_id: 1, whiskey_id: 11, comment: "spicy sweet, smooth w/ water")
Comment.create(member_id: 1, whiskey_id: 12, comment: "bite, floral, water +")
Comment.create(member_id: 1, whiskey_id: 13, comment: "everyday")
Comment.create(member_id: 1, whiskey_id: 14, comment: "salt, smoke, peat")
Comment.create(member_id: 1, whiskey_id: 15, comment: "honey, floral, water +")
Comment.create(member_id: 1, whiskey_id: 16, comment: "peat, smoke, water -")
Comment.create(member_id: 1, whiskey_id: 17, comment: "seaweed")
Comment.create(member_id: 1, whiskey_id: 18, comment: "seaweed, seagulls nuts, water -")
Comment.create(member_id: 1, whiskey_id: 19, comment: "smooth, water +")
Comment.create(member_id: 1, whiskey_id: 20, comment: "fire, robust, smokey, water +")
Comment.create(member_id: 1, whiskey_id: 21, comment: "potent beast, walty, fire, water +")
Comment.create(member_id: 1, whiskey_id: 22, comment: "flowery")
Comment.create(member_id: 1, whiskey_id: 23, comment: "orange, water +")
Comment.create(member_id: 1, whiskey_id: 24, comment: "bite, floral, water ++")
Comment.create(member_id: 1, whiskey_id: 25, comment: "cigar, burn, peaty")
Comment.create(member_id: 1, whiskey_id: 26, comment: "honey, sweet burn, water +")
Comment.create(member_id: 1, whiskey_id: 27, comment: "water +, flavorful")
Comment.create(member_id: 1, whiskey_id: 28, comment: "water +, honey")
Comment.create(member_id: 1, whiskey_id: 29, comment: "scotch-y, salty, nutty")
Comment.create(member_id: 1, whiskey_id: 29, comment: "spice kick, water +")
Comment.create(member_id: 1, whiskey_id: 29, comment: "smooth, water -")
Comment.create(member_id: 1, whiskey_id: 30, comment: "smokey")
Comment.create(member_id: 1, whiskey_id: 31, comment: "daily drink")
Comment.create(member_id: 1, whiskey_id: 32, comment: "did not cut")
Comment.create(member_id: 1, whiskey_id: 33, comment: "daily drink, pepper")
Comment.create(member_id: 1, whiskey_id: 34, comment: "water +")
Comment.create(member_id: 1, whiskey_id: 35, comment: "water ++")
Comment.create(member_id: 1, whiskey_id: 35, comment: "cigar +")
Comment.create(member_id: 1, whiskey_id: 42, comment: "fiery, smokey, peaty, salty")
Comment.create(member_id: 1, whiskey_id: 43, comment: "bite, water +")
Comment.create(member_id: 1, whiskey_id: 44, comment: "summer, water +")
Comment.create(member_id: 1, whiskey_id: 45, comment: "seems mild for Lagavulin")
Comment.create(member_id: 1, whiskey_id: 46, comment: "smooth, water +, citrus")
Comment.create(member_id: 1, whiskey_id: 47, comment: "pepper kick, water ++")
Comment.create(member_id: 1, whiskey_id: 48, comment: "holy crapa, I'm drinkin' scapa, sea")
Comment.create(member_id: 1, whiskey_id: 49, comment: "smooth")
Comment.create(member_id: 1, whiskey_id: 50, comment: "water -, caramel")
Comment.create(member_id: 1, whiskey_id: 51, comment: "salty")
Comment.create(member_id: 1, whiskey_id: 52, comment: "peatier than 12")
Comment.create(member_id: 1, whiskey_id: 52, comment: "smooth for Islay")
Comment.create(member_id: 1, whiskey_id: 53, comment: "water -, spicy")
Comment.create(member_id: 1, whiskey_id: 54, comment: "Scotch, need to acquire, water +")
Comment.create(member_id: 1, whiskey_id: 55, comment: "smooth")
Comment.create(member_id: 1, whiskey_id: 55, comment: "water ++, light sweetness, mellow nose")
Comment.create(member_id: 1, whiskey_id: 56, comment: "****bottle watered in error/ OMIT*****")
Comment.create(member_id: 1, whiskey_id: 57, comment: "water +, dry, Scotch")
Comment.create(member_id: 1, whiskey_id: 58, comment: "Scotch, need to acquire, water +")
Comment.create(member_id: 1, whiskey_id: 59, comment: "mellower than the 10")
Comment.create(member_id: 1, whiskey_id: 60, comment: "seaweed, smoke")
Comment.create(member_id: 1, whiskey_id: 61, comment: "water -, Chardonnay-like, clean")
Comment.create(member_id: 1, whiskey_id: 62, comment: "unchill blend (16yr + 6yr), sweet, afterburn")
Comment.create(member_id: 1, whiskey_id: 63, comment: "too mellow, sweet")
Comment.create(member_id: 1, whiskey_id: 64, comment: "sweet, smooth, light burn aftershock")
Comment.create(member_id: 1, whiskey_id: 65, comment: "smokey, peaty, salty, earthy, sherry cask")
Comment.create(member_id: 1, whiskey_id: 66, comment: "sweet, light, vanilla notes, caramel")
Comment.create(member_id: 1, whiskey_id: 67, comment: "1 sherry, 2 bourbon, 2 bordeaux casks, peat, mild sweet/honey ****")
Comment.create(member_id: 1, whiskey_id: 68, comment: "peppery, crisp, slight burn, A-cup w/ water")
Comment.create(member_id: 1, whiskey_id: 69, comment: "peat bomb, buttery, mild salt, Tyson one trick punch, unexpectedly pleasant")
Comment.create(member_id: 1, whiskey_id: 70, comment: "less peaty, smoke, water -")
Comment.create(member_id: 1, whiskey_id: 71, comment: "highlands, heavily peated, sea, cinnamon")
Comment.create(member_id: 1, whiskey_id: 72, comment: "bite, salty, smooth, less complex than Ardbeg Alligator")
Comment.create(member_id: 1, whiskey_id: 73, comment: "burn, bright, no peat, quick, smoky finish")
Comment.create(member_id: 1, whiskey_id: 74, comment: "smoke, peat")
Comment.create(member_id: 1, whiskey_id: 75, comment: "super pear, easy , pleasant, smooth, light")
Comment.create(member_id: 1, whiskey_id: 76, comment: "peat ass-kicker, nutty")
Comment.create(member_id: 1, whiskey_id: 76, comment: "The standard")
Comment.create(member_id: 1, whiskey_id: 77, comment: "nose burn, sea, milder than 10, iodine")
Comment.create(member_id: 1, whiskey_id: 78, comment: "mild rose, burn, seaweed, brine, sharp")
Comment.create(member_id: 1, whiskey_id: 78, comment: "light peat, bite, brine")
Comment.create(member_id: 1, whiskey_id: 79, comment: "clean, crisp, sweet, vanilla, white wine")
Comment.create(member_id: 1, whiskey_id: 79, comment: "hot nose, good burn, rose essence, smooth")
Comment.create(member_id: 1, whiskey_id: 80, comment: "sweet burn, spicy, ice +")
Comment.create(member_id: 1, whiskey_id: 80, comment: "very corn-y in smell and taste, unique, full-bodied, no burn, musky")
Comment.create(member_id: 1, whiskey_id: 81, comment: "smooth like Irish Whisky (Jameson -like), caramel, honey")
Comment.create(member_id: 1, whiskey_id: 82, comment: "nose hot, burns, ice +, everyday, nothing special")
Comment.create(member_id: 1, whiskey_id: 83, comment: "Distillery only, burn nose, exceptional, hot, water +, ice+, neat +")
Comment.create(member_id: 1, whiskey_id: 84, comment: "smoky, peaty, salty, super smoke")
Comment.create(member_id: 1, whiskey_id: 85, comment: "smells hot, clean, light smoke & peat, YOUNG")
Comment.create(member_id: 1, whiskey_id: 86, comment: "spicy, hot, alcohol forward, green apple hints,  water + - STRONG!")
Comment.create(member_id: 1, whiskey_id: 87, comment: "Bourbon is profound, sweet, mild, low peat")
Comment.create(member_id: 1, whiskey_id: 87, comment: "smells of the sea, spicy bite, ild smokiness, peat forward, deep, should be mellow but it's not")
Comment.create(member_id: 1, whiskey_id: 88, comment: "buttery, smooth, mellow, orange, milder than the nose")
Comment.create(member_id: 1, whiskey_id: 89, comment: "oakiness, heavy, molasses, frisky, bite")
Comment.create(member_id: 1, whiskey_id: 90, comment: "post wood finish, sweet, not woody")
Comment.create(member_id: 1, whiskey_id: 91, comment: "non-chill filtered, hot nose, campfire, sweet finish, chocolate")
Comment.create(member_id: 1, whiskey_id: 92, comment: "mellow, woody, mild afterburn, daily…")
Comment.create(member_id: 1, whiskey_id: 93, comment: "mild peat, lemon/apple hints, chardonnay/muscat, smooth, sweet, buttery")
Comment.create(member_id: 1, whiskey_id: 94, comment: "peat heaven, not super smoky, vatted, pleasant, vibrant, briny, This is why I drink whisky - RG")
Comment.create(member_id: 1, whiskey_id: 95, comment: "nose f-ing heavenly, mild, sweet, silkysmooth")
Comment.create(member_id: 1, whiskey_id: 96, comment: "Oban-esque, burn, fruit forward, biny nose")
Comment.create(member_id: 1, whiskey_id: 97, comment: "dark, barrel wood char, hot, spice")
Comment.create(member_id: 1, whiskey_id: 98, comment: "hot nose, mild, rye-ish, sweet, vanilla")
Comment.create(member_id: 1, whiskey_id: 99, comment: "Rye-Bourbon-Scotch blend, smoky, sweet, briny, smoke dissapates quickly")
Comment.create(member_id: 1, whiskey_id: 100, comment: "hot nose, Bardstown, sweet, caramel, Bourbon")
Comment.create(member_id: 1, whiskey_id: 101, comment: "non-descript, thin")
Comment.create(member_id: 1, whiskey_id: 102, comment: "hot nose, peat, brine")
Comment.create(member_id: 1, whiskey_id: 103, comment: "Bourbon cask, Petrus Cask, bottled at Bruichladdich, caramel, mellow raisin")
Comment.create(member_id: 1, whiskey_id: 104, comment: "Cask Strength Unchillfiltered, smells of ocean, hot, peat, smoke, almond")
Comment.create(member_id: 1, whiskey_id: 105, comment: "peat ass-kicker, nutty")
Comment.create(member_id: 1, whiskey_id: 106, comment: "2nd tasting, hot nose, peat, brine")
Comment.create(member_id: 1, whiskey_id: 107, comment: "creamy, super smooth, buttery, oaky, butterscotch, hot nose, caramel")
Comment.create(member_id: 1, whiskey_id: 108, comment: "maturedin Hogshead, spicy, not nose, alochol-y, raisin")
Comment.create(member_id: 1, whiskey_id: 109, comment: "caramel, smooth, the standard")
Comment.create(member_id: 1, whiskey_id: 110, comment: "tasty nose, caramel, toffee, smooth, dry, not brine-y, sweet, citrus, waxy")
Comment.create(member_id: 1, whiskey_id: 111, comment: "Bardstown, sweet nose, sweet heat, a bite")
Comment.create(member_id: 1, whiskey_id: 111, comment: "wheat (Makers-ish), not not, sweet, easy drinking everyday")
Comment.create(member_id: 1, whiskey_id: 112, comment: "light heat on nose, spice, complex")
Comment.create(member_id: 1, whiskey_id: 113, comment: "sweet corn, light charcoal, leather smell.  Rye & Bourbon blend")
Comment.create(member_id: 1, whiskey_id: 114, comment: "Non Chill Filtered, clean, not hot, earthiness, it's own beast")
Comment.create(member_id: 1, whiskey_id: 115, comment: "Island malt, double matured in amoruso oak, bbq, smoke")
Comment.create(member_id: 1, whiskey_id: 116, comment: "disappointingly mild, Oban-like, lacks complexity, far from stormy")
Comment.create(member_id: 1, whiskey_id: 117, comment: "Super Mild, a little too much so, good mixer")
